version: '3.4'

services:
  xmpp-server:
    build: ./prosody
    ports:
      - "5222:5222"
    expose:
      - "5347"
    volumes:
      - ./prosody/localhost.cfg.lua:/etc/prosody/conf.d/localhost.cfg.lua:Z
      - ./prosody/data:/var/lib/prosody:Z
  prekeys-raw:
    build: ./raw
    command: -address 0.0.0.0 -port 30123 -identity "${PREKEY_SERVER_IDENTITY}" -key-file /secrets/server.keys -storage dir:/keys
    volumes:
      - ./secrets:/secrets:Z
      - ./keys:/keys:Z
    expose:
      - "30123"
  prekeys-xmpp:
    build: ./xmpp
    command: -raw-address prekeys-raw -raw-port 30123 -xmpp-address xmpp-server -xmpp-port 5347 -shared-secret "${XMPP_COMPONENTS_SECRET}" -name "${PREKEY_SERVER_IDENTITY}" -fingerprint "${PREKEY_SERVER_FINGERPRINT}"
    depends_on:
      - prekeys-raw
      - xmpp-server

